project:
  type: website
website:
  title: ""
  site-url: https://r-htalmicstest.org
  navbar:
    logo: "assets/images/logo2-removebg-preview.png"   # Logo will link to index.qmd by default
    left:
      - href: about.qmd
        text: About
      - href: workshops.qmd
        text: Workshops
      - href: resrcs.qmd
        text: Learning Resources
      - href: commitee.qmd
        text: Committee
      - href: contact.qmd
        text: Contact Us
 
format:
  html:
    theme: yeti #lux #yeti #lumen #simplex #lumen #yeti   #  litera     # or 'minty', 'flatly', etc.
    toc: true
    css: styles.css
    page-layout: full
    include-after-body: _footer.html
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
          <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet">
      - navbar-subtitle.html
editor: visual
