name: Deploy Quarto Website

on:
  push:
    branches: [main]   # or master, depending on your branch
  workflow_dispatch:    # allows manual trigger

permissions:
  contents: write       # needed for deployment

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"

      - name: Setup Pandoc (optional, but often needed)
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R (optional, if you use R in Quarto)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - name: Install R packages (optional, adjust as needed)
        if: fileExists('renv.lock')
        uses: r-lib/actions/setup-renv@v2

      - name: Render Quarto Project
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
